### PR TITLE
fix: Added retries to ebs-autoscaling download script (resolves #186)

### LINKED ISSUE #186: EBS data volume not mounted for some Nextflow jobs
Some of the jobs submitted with Nextflow do not mount the 200GB data disk, resulting in "No space left on device" error. This happens only with a few random jobs.

**Steps to Reproduce**

agc workflow run demo-nextflow-project --context spotCtx

**Relevant Logs**

I get this below error:
 |abort: write error ....(No space left on device)

Doing a df -h on the instance shows the 200GB disk (/dev/nvme1n1) not being mounted:

>>  df -h
  | Filesystem Size Used Avail Use% Mounted on
  | overlay 30G 9.4G 20G 33% /
  | tmpfs 64M 0 64M 0% /dev
  | tmpfs 5.0G 0 5.0G 0% /sys/fs/cgroup
  | /dev/nvme0n1p1 30G 9.4G 20G 33% /opt/aws-cli
  | shm 64M 0 64M 0% /dev/shm
  | tmpfs 5.0G 0 5.0G 0% /proc/acpi
  | tmpfs 5.0G 0 5.0G 0% /sys/firmware

**Expected Behavior**
Mount the 200GB disk (/dev/nvme1n1 ) on /
>> df -h
 | Filesystem Size Used Avail Use% Mounted on
 **| /dev/nvme1n1 200G 12G 188G 6% /**
 | tmpfs 64M 0 64M 0% /dev
 | tmpfs 3.8G 0 3.8G 0% /sys/fs/cgroup
 | /dev/nvme0n1p1 30G 6.4G 23G 22% /opt/aws-cli
 | /dev/nvme1n1 200G 12G 188G 6% /etc/hosts
 | shm 64M 0 64M 0% /dev/shm
 | tmpfs 3.8G 0 3.8G 0% /proc/acpi
 | tmpfs 3.8G 0 3.8G 0% /sys/firmware

**Actual Behavior**

See above expected behavior

Operating System:
AGC Version: agc version: 1.0.0-41-gc5ac696
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

### PR DESCRIPTION
**Pull request by waliag87**
Issue #, if available:

Users were seeing ebs volumes not being mounted sporadically. This must come from either the script failing to download and/or execute ebs-autoscaling. 

[//]: #  (A description of the change that you made and the new user experience that it creates)

**Description of how you validated changes**

[//]: #  (A description of you validated your changes and any relevant logs that show your change works)

Validated by deploying agc to my personal account and updating the `get-amazon-ebs-autoscale.sh` in my s3 bucket to include this new code. I then validated via ec2 system logs that we were successfully seeing the new code:
```
[   28.504624] cloud-init[3796]: + local s3_path=s3://agc-987650158744-us-west-2/batch-artifacts/amazon-ebs-autoscale.tgz
[   28.504905] cloud-init[3796]: + local destination=./amazon-ebs-autoscale.tgz
[   28.505224] cloud-init[3796]: + for i in '{1..5}'
[   28.505414] cloud-init[3796]: + [[ s3://agc-987650158744-us-west-2/batch-artifacts/amazon-ebs-autoscale.tgz =~ s3://([^/]+)/(.+) ]]
[   28.505616] cloud-init[3796]: + bucket=agc-987650158744-us-west-2
[   28.506801] cloud-init[3796]: + key=batch-artifacts/amazon-ebs-autoscale.tgz
[   28.507023] cloud-init[3796]: ++ aws s3api head-object --bucket agc-987650158744-us-west-2 --key batch-artifacts/amazon-ebs-autoscale.tgz --query ContentLength
[[32m  OK  [0m] Started Dynamically Generate Message Of The Day.
[[32m  OK  [0m] Reached target Multi-User System.
[[32m  OK  [0m] Reached target Graphical Interface.
         Starting Update UTMP about System Runlevel Changes...
[[32m  OK  [0m] Started Update UTMP about System Runlevel Changes.
[   29.217982] cloud-init[3796]: + content_length=16574
[   29.218434] cloud-init[3796]: + aws s3 cp --no-progress s3://agc-987650158744-us-west-2/batch-artifacts/amazon-ebs-autoscale.tgz ./amazon-ebs-autoscale.tgz
[   29.760345] cloud-init[3796]: download: s3://agc-987650158744-us-west-2/batch-artifacts/amazon-ebs-autoscale.tgz to ./amazon-ebs-autoscale.tgz
[   29.826794] cloud-init[3796]: ++ LC_ALL=C
[   29.827652] cloud-init[3796]: ++ ls -dn -- ./amazon-ebs-autoscale.tgz
[   29.829102] cloud-init[3796]: ++ awk '{print $5; exit}'
[   29.830508] cloud-init[3796]: + [[ 16574 -eq 16574 ]]
[   29.831498] cloud-init[3796]: + break
[   29.832323] cloud-init[3796]: + tar -xzvf amazon-ebs-autoscale.tgz
```

Also confirmed presence of volume:
```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        1.9G     0  1.9G   0% /dev
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           1.9G  472K  1.9G   1% /run
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/nvme0n1p1   30G  6.4G   24G  22% /
/dev/nvme1n1    200G  786M  199G   1% /var/lib/docker
tmpfs           389M     0  389M   0% /run/user/0
```

**Checklist**

- [Y] If this change would make any existing documentation invalid, I have included those updates within this PR
- [N/A ] I have added unit tests that prove my fix is effective or that my feature works
- [Y] I have linted my code before raising the PR
- [Y ] Title of this Pull Request follows Conventional Commits standard: https://www.conventionalcommits.org/en/v1.0.0/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by markjschreiber — DISMISSED** [review]

File: packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/get-amazon-ebs-autoscale.sh [hunk 1]
```diff
@@ -98,6 +98,33 @@ function latest() {
...
+    aws s3 cp --no-progress "$s3_path" "$destination" &&
+    [[ $(LC_ALL=C ls -dn -- "$destination" | awk '{print $5; exit}') -eq "$content_length" ]] &&
+    break || echo "attempt $i to copy $s3_path failed";
+
+    if [ "$i" -eq 5 ]; then
+        echo "failed to copy $s3_path after $i attempts. aborting"
+        exit 2
+    fi
+    sleep $((7 * $i))
+    done
```
Comment (tneely) [inline packages/cdk/lib/artifacts/batch-artifacts/ecs-additions/get-amazon-ebs-autoscale.sh:125]: nit: can you indent this?

e.g. 

```
for i in {1..5}; do
    if [[ s3_path ...
done
```

**Review by tneely — CHANGES_REQUESTED** [review]

**Review by tneely — APPROVED** [review]
